Controllers/AuctionController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyApp.Models;
using MyApp.Repositories;

namespace MyApp.Controllers
{
    
    public class AuctionController: Controller
    {
        private readonly IAuctionRepository _auctionRepository;
        private readonly IBidRepository _bidRepository;
        public AuctionController(IAuctionRepository auctionRepository, IBidRepository bidRepository)
        {
            _auctionRepository = auctionRepository;
            _bidRepository = bidRepository;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            Console.WriteLine("IsAuthenticated: " + User.Identity.IsAuthenticated + " User: " + User.Identity.Name);
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Details(int id)
        {
            var auction = _auctionRepository.GetById(id);
            Console.WriteLine("Auction Details: " + auction.Name);
            ViewData["AuctionId"] = auction.Id;
            var highestBid = _bidRepository.GetHighestBidForAuction(id);
            ViewBag.HighestBid = highestBid?.Price ?? auction.PriceStart;
            Console.WriteLine("Highest Bid: " + ViewBag.HighestBid);
            return View(auction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(Auction auction)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            if (userIdClaim == null)
            {
                return Unauthorized();
            }
            if (auction.TimeEnd <= auction.TimeStart || auction.TimeStart <= DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "Thời gian không hợp lệ.");
            }
            auction.UserId = int.Parse(userIdClaim.Value);
            auction.Status = AuctionStatus.Pending;

            if (!ModelState.IsValid)
{
    foreach (var entry in ModelState)
    {
        foreach (var error in entry.Value.Errors)
        {
            Console.WriteLine($"Lỗi tại {entry.Key}: {error.ErrorMessage}");
        }
    }
}

            if (ModelState.IsValid)
            {
                _auctionRepository.Add(auction);
                _auctionRepository.Save();

                return RedirectToAction("Index", "Home");
            }

            return View(auction);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ApprovedAuctions()
        {
            var approvedAuctions = _auctionRepository.GetApprovedAuctions();
            return View(approvedAuctions);
        }
        [HttpGet]
        [AllowAnonymous]

        public IActionResult ActiveAuctions()
        {
            var activeAuctions = _auctionRepository.GetActiveAuctions();
            return View(activeAuctions);
        }
        public IActionResult Index()
        {
            var auctions = _auctionRepository.GetAllAuctionsWithDetails();
            return View(auctions);
        }
        public IActionResult UpdateStatus(int auctionId, AuctionStatus status)
        {
            _auctionRepository.UpdateStatus(auctionId, status);
            _auctionRepository.Save();
            Console.WriteLine($"Updated Auction ID {auctionId} to Status {status}");
            return Ok();
        }

    }
}

Controllers/BidController.cs
using Microsoft.AspNetCore.SignalR;
using MyApp.Hubs;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using MyApp.Models;
using MyApp.Repositories;
using Microsoft.AspNetCore.Authorization;


namespace MyApp.Controllers
{
    [Authorize]
    public class BidController : Controller
    {
        private readonly IBidRepository _bidRepository;
        private readonly IAuctionRepository _auctionRepository;
        private readonly IHubContext<AuctionHub> _hubContext;

        public BidController(IBidRepository bidRepository, IAuctionRepository auctionRepository, IHubContext<AuctionHub> hubContext)
        {
            _bidRepository = bidRepository;
            _auctionRepository = auctionRepository;
            _hubContext = hubContext;

        }
        [HttpPost]
        
        public async Task<IActionResult> PlaceBid(int auctionId, decimal bidAmount)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var auction = _auctionRepository.GetById(auctionId);
            var userId = int.Parse(userIdClaim.Value);
            Console.WriteLine("Auction: " + (auction != null ? auction.PriceStart : "None"));
            if (auction == null || auction.Status != AuctionStatus.Approved)
            {
                return BadRequest("Phiên đấu giá không hợp lệ.");
            }
            var highestBid = _bidRepository.GetHighestBidForAuction(auctionId);
            Console.WriteLine("Highest Bid: " + (highestBid != null ? highestBid.Price.ToString() : auction.PriceStart.ToString()));
            var minBidAmount = highestBid != null ? highestBid.Price + 1 : auction.PriceStart;
            Console.WriteLine("Min Bid Amount: " + minBidAmount);
            Console.WriteLine("Bid Amount: " + bidAmount);
            if (bidAmount < minBidAmount)
            {
                return BadRequest($"Giá đặt phải cao hơn ít nhất 1 đơn vị so với giá hiện tại: {minBidAmount}");
            }
            if (auction.UserId == userId)
            {
                return BadRequest("Bạn không thể đấu giá sản phẩm của chính mình.");
            }

            var bid = new Bid
            {
                AuctionID = auctionId,
                UserID = int.Parse(userIdClaim.Value),
                Price = bidAmount,
                Time = DateTime.Now
            };

            _bidRepository.Add(bid);
            _bidRepository.Save();
            await _hubContext.Clients.All.SendAsync("ReceiveHighestBid", auctionId, bid.Price);
            // return RedirectToAction("Details", "Auction", new { id = auctionId });

            return Ok();

        }
        public IActionResult Index()
        {
            var userRoleClaim = User.FindFirst(ClaimTypes.Role);
            Console.WriteLine("User Role Claim: " + (userRoleClaim != null ? userRoleClaim.Value : "None"));
            var role = int.Parse(userRoleClaim.Value);
            if (role != 1)
            {
                return Forbid();
            }
            var bids = _bidRepository.GetAllBilsWithDetails();
            return View(bids);
        }
    }
}

Controllers/PaymentController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyApp.Models;
using MyApp.Repositories;

namespace MyApp.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
   private readonly IPaymentRepository _paymentRepository;

        public PaymentController(IPaymentRepository paymentRepository)
        {
            _paymentRepository = paymentRepository;
        }

        public IActionResult Index()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            Console.WriteLine("User ID Claim: " + (userIdClaim != null ? userIdClaim.Value : "None"));
            var userRoleClaim = User.FindFirst(ClaimTypes.Role);
            Console.WriteLine("User Role Claim: " + (userRoleClaim != null ? userRoleClaim.Value : "None"));
            var role = int.Parse(userRoleClaim.Value);
            if (role != 1)
            {
                return Forbid();
            }
            var payments = _paymentRepository.GetAllPaymentsWithDetails();
            return View(payments);
        }
        public IActionResult UpdatePaymentStatus(int paymentId, PaymentStatus newStatus)
        {
            _paymentRepository.UpdateStatus(paymentId, newStatus);
            return Ok();
        }
    }
}

Controllers/UserController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyApp.Models;
using MyApp.Repositories;

namespace MyApp.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
   private readonly IUserRepository _userRepository;

        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            Console.WriteLine("User ID Claim: " + (userIdClaim != null ? userIdClaim.Value : "None"));
            var userRoleClaim = User.FindFirst(ClaimTypes.Role);
            Console.WriteLine("User Role Claim: " + (userRoleClaim != null ? userRoleClaim.Value : "None"));
            var role = int.Parse(userRoleClaim.Value);
            if (role != 1)
            {
                return Forbid();
            }
            var users = _userRepository.GetAll();
            return View(users);
        }
        public IActionResult Details(int id)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);

            var user = _userRepository.GetById(userIdClaim != null ? int.Parse(userIdClaim.Value) : 0);
            Console.WriteLine("Fetched User: " + (user != null ? user.Name : "None"));
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

   
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Đấu giá</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 d-flex justify-content-evenly">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="User" asp-action="Index">Quản lý người dùng</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Auction" asp-action="Index">Quản lý phiên đấu giá</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Bid" asp-action="Index">Quản lý đấu giá</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Payment" asp-action="Index">Quản lý Thanh toán</a>
        </li>
      </ul>
      @* <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> *@
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MyApp - Phạm Đức Anh - Bảo Nguyên -Hà Văn Cảnh
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Auction</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-evenly w-100 text-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="ApprovedAuctions">Lịch đấu giá</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="ActiveAuctions">Phiên trực tuyến</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="Create">Người dùng</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Đăng xuất</a>
                            </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Đăng nhập</a>
                        </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MyApp - Phạm Đức Anh - Bảo Nguyên -Hà Văn Cảnh
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>